// One-shot generator for lib/geo/worldPath.ts.
// Projects Natural Earth 110m land onto an equirectangular projection whose
// parameters are re-exported so runtime code can project lat/lng points with
// plain arithmetic (no d3 in the client bundle).
//
// Usage: node scripts/generateWorldPath.mjs
import { geoEquirectangular, geoPath } from "d3-geo";
import { feature } from "topojson-client";
import { createRequire } from "module";
import { writeFileSync } from "fs";

const require = createRequire(import.meta.url);
const world = require("world-atlas/land-110m.json");

const WIDTH = 1000;
const HEIGHT = 460;

const projection = geoEquirectangular().fitSize([WIDTH, HEIGHT], feature(world, world.objects.land));
const path = geoPath(projection);
const d = path(feature(world, world.objects.land));

const [tx, ty] = projection.translate();
const scale = projection.scale();

const out = `// AUTO-GENERATED by scripts/generateWorldPath.mjs — do not edit by hand.
// Natural Earth 110m land, equirectangular projection.

export const WORLD_MAP_WIDTH = ${WIDTH};
export const WORLD_MAP_HEIGHT = ${HEIGHT};

// Projection parameters (d3.geoEquirectangular equivalents).
const SCALE = ${scale};
const TRANSLATE_X = ${tx};
const TRANSLATE_Y = ${ty};

/** Projects [lat, lng] (degrees) to SVG [x, y] in the map's viewBox. */
export function projectPoint(lat: number, lng: number): [number, number] {
  const x = TRANSLATE_X + SCALE * (lng * Math.PI / 180);
  const y = TRANSLATE_Y - SCALE * (lat * Math.PI / 180);
  return [x, y];
}

export const WORLD_LAND_PATH = ${JSON.stringify(d)};
`;

writeFileSync(new URL("../lib/geo/worldPath.ts", import.meta.url), out);
console.log(`worldPath.ts written (${(d.length / 1024).toFixed(1)} KB path)`);
